spring.application.name=SmartStock

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_stock
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update

api.security.token.secret=${JWT_SECRET:7f3c9a2e1d8b6f4a0c5e7d9b3a1f8c6e2d4b7a9f0c3e5d8b1a6f9c2e7d4b8a}
