spring.application.name=SmartStock

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_stock
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update